version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    env_file:
      - samba.env
    networks:
      - default
    ports:
      - "137:137/udp" # required to advertise shares (NMBD)
      - "138:138/udp" # required to advertise shares (NMBD)
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - ./files:/mnt:z # :z allows share to be used by multiple containers

networks:
    default:
